import { eventHandler } from 'h3';

import { verifyAccessToken } from '~/utils/jwt-utils';
import { unAuthorizedResponse, useResponseSuccess } from '~/utils/response';

// ERP 菜单树数据 - 完整的 11 个模块
const ERP_MENU_TREE = [
  {
    id: 'iam',
    name: 'IAM',
    title: 'IAM (身份与访问)',
    icon: 'lucide:shield-check',
    level: 1,
    order: 1,
    moduleCode: 'IAM',
    children: [
      {
        id: 'iam-identity',
        parentId: 'iam',
        name: 'Identity',
        title: '身份管理',
        icon: 'lucide:users',
        level: 2,
        order: 1,
        moduleCode: 'IAM',
        children: [
          {
            id: 'iam-users',
            parentId: 'iam-identity',
            name: 'Users',
            title: '用户管理',
            icon: 'lucide:user',
            path: '/iam/users',
            level: 3,
            order: 1,
            moduleCode: 'IAM',
          },
          {
            id: 'iam-groups',
            parentId: 'iam-identity',
            name: 'Groups',
            title: '用户组',
            icon: 'lucide:users-round',
            path: '/iam/groups',
            level: 3,
            order: 2,
            moduleCode: 'IAM',
          },
        ],
      },
      {
        id: 'iam-access',
        parentId: 'iam',
        name: 'Access',
        title: '访问控制',
        icon: 'lucide:lock',
        level: 2,
        order: 2,
        moduleCode: 'IAM',
        children: [
          {
            id: 'iam-rbac',
            parentId: 'iam-access',
            name: 'RBAC',
            title: '角色权限',
            icon: 'lucide:shield',
            path: '/iam/rbac',
            level: 3,
            order: 1,
            moduleCode: 'IAM',
          },
          {
            id: 'iam-policy',
            parentId: 'iam-access',
            name: 'Policy',
            title: '策略管理',
            icon: 'lucide:file-lock',
            path: '/iam/policy',
            level: 3,
            order: 2,
            moduleCode: 'IAM',
          },
        ],
      },
      {
        id: 'iam-tenancy',
        parentId: 'iam',
        name: 'Tenancy',
        title: '租户管理',
        icon: 'lucide:building',
        level: 2,
        order: 3,
        moduleCode: 'IAM',
        children: [
          {
            id: 'iam-tenants',
            parentId: 'iam-tenancy',
            name: 'Tenants',
            title: '租户列表',
            icon: 'lucide:building-2',
            path: '/iam/tenants',
            level: 3,
            order: 1,
            moduleCode: 'IAM',
          },
        ],
      },
    ],
  },
  {
    id: 'mdm',
    name: 'MDM',
    title: 'MDM (主数据)',
    icon: 'lucide:database',
    level: 1,
    order: 2,
    moduleCode: 'MDM',
    children: [
      {
        id: 'mdm-material',
        parentId: 'mdm',
        name: 'Material',
        title: '物料主数据',
        icon: 'lucide:package',
        level: 2,
        order: 1,
        moduleCode: 'MDM',
        children: [
          {
            id: 'mdm-products',
            parentId: 'mdm-material',
            name: 'Products',
            title: '产品管理',
            icon: 'lucide:box',
            path: '/mdm/products',
            level: 3,
            order: 1,
            moduleCode: 'MDM',
          },
        ],
      },
      {
        id: 'mdm-bp',
        parentId: 'mdm',
        name: 'BP',
        title: '业务伙伴',
        icon: 'lucide:handshake',
        level: 2,
        order: 2,
        moduleCode: 'MDM',
        children: [
          {
            id: 'mdm-vendors',
            parentId: 'mdm-bp',
            name: 'Vendors',
            title: '供应商',
            icon: 'lucide:truck',
            path: '/mdm/vendors',
            level: 3,
            order: 1,
            moduleCode: 'MDM',
          },
          {
            id: 'mdm-customers',
            parentId: 'mdm-bp',
            name: 'Customers',
            title: '客户',
            icon: 'lucide:user-check',
            path: '/mdm/customers',
            level: 3,
            order: 2,
            moduleCode: 'MDM',
          },
        ],
      },
    ],
  },
  {
    id: 'fi',
    name: 'FI',
    title: 'FI (财务管理)',
    icon: 'lucide:wallet',
    level: 1,
    order: 3,
    moduleCode: 'FI',
    children: [
      {
        id: 'fi-gl',
        parentId: 'fi',
        name: 'GL',
        title: '总账',
        icon: 'lucide:book-open',
        level: 2,
        order: 1,
        moduleCode: 'FI',
        children: [
          {
            id: 'fi-vouchers',
            parentId: 'fi-gl',
            name: 'Vouchers',
            title: '凭证处理',
            icon: 'lucide:file-text',
            path: '/fi/vouchers',
            level: 3,
            order: 1,
            moduleCode: 'FI',
          },
          {
            id: 'fi-coa',
            parentId: 'fi-gl',
            name: 'CoA',
            title: '会计科目表',
            icon: 'lucide:list',
            path: '/fi/coa',
            level: 3,
            order: 2,
            moduleCode: 'FI',
          },
        ],
      },
      {
        id: 'fi-apar',
        parentId: 'fi',
        name: 'APAR',
        title: '应付应收',
        icon: 'lucide:receipt',
        level: 2,
        order: 2,
        moduleCode: 'FI',
        children: [
          {
            id: 'fi-ap',
            parentId: 'fi-apar',
            name: 'AP',
            title: '应付账款',
            icon: 'lucide:arrow-down-circle',
            path: '/fi/ap',
            level: 3,
            order: 1,
            moduleCode: 'FI',
          },
          {
            id: 'fi-ar',
            parentId: 'fi-apar',
            name: 'AR',
            title: '应收账款',
            icon: 'lucide:arrow-up-circle',
            path: '/fi/ar',
            level: 3,
            order: 2,
            moduleCode: 'FI',
          },
        ],
      },
    ],
  },
  {
    id: 'scm',
    name: 'SCM',
    title: 'SCM (供应链)',
    icon: 'lucide:truck',
    level: 1,
    order: 4,
    moduleCode: 'SCM',
    children: [
      {
        id: 'scm-im',
        parentId: 'scm',
        name: 'IM',
        title: '库存管理',
        icon: 'lucide:warehouse',
        level: 2,
        order: 1,
        moduleCode: 'SCM',
        children: [
          {
            id: 'scm-inventory',
            parentId: 'scm-im',
            name: 'Inventory',
            title: '库存概览',
            icon: 'lucide:package-search',
            path: '/scm/inventory',
            level: 3,
            order: 1,
            moduleCode: 'SCM',
          },
          {
            id: 'scm-movements',
            parentId: 'scm-im',
            name: 'Movements',
            title: '货物移动',
            icon: 'lucide:move',
            path: '/scm/movements',
            level: 3,
            order: 2,
            moduleCode: 'SCM',
          },
        ],
      },
    ],
  },
  {
    id: 'mfg',
    name: 'MFG',
    title: 'MFG (生产制造)',
    icon: 'lucide:factory',
    level: 1,
    order: 5,
    moduleCode: 'MFG',
    children: [
      {
        id: 'mfg-pp',
        parentId: 'mfg',
        name: 'PP',
        title: '生产计划',
        icon: 'lucide:calendar-check',
        level: 2,
        order: 1,
        moduleCode: 'MFG',
        children: [
          {
            id: 'mfg-orders',
            parentId: 'mfg-pp',
            name: 'Orders',
            title: '生产订单',
            icon: 'lucide:clipboard-list',
            path: '/mfg/orders',
            level: 3,
            order: 1,
            moduleCode: 'MFG',
          },
        ],
      },
    ],
  },
  {
    id: 'sd',
    name: 'SD',
    title: 'SD (销售分销)',
    icon: 'lucide:shopping-cart',
    level: 1,
    order: 6,
    moduleCode: 'SD',
    children: [
      {
        id: 'sd-sales',
        parentId: 'sd',
        name: 'Sales',
        title: '销售处理',
        icon: 'lucide:shopping-bag',
        level: 2,
        order: 1,
        moduleCode: 'SD',
        children: [
          {
            id: 'sd-orders',
            parentId: 'sd-sales',
            name: 'Orders',
            title: '销售订单',
            icon: 'lucide:file-plus',
            path: '/sd/orders',
            level: 3,
            order: 1,
            moduleCode: 'SD',
          },
        ],
      },
    ],
  },
  {
    id: 'pm',
    name: 'PM',
    title: 'PM (项目管理)',
    icon: 'lucide:folder-kanban',
    level: 1,
    order: 7,
    moduleCode: 'PM',
    children: [
      {
        id: 'pm-portfolio',
        parentId: 'pm',
        name: 'Portfolio',
        title: '项目组合',
        icon: 'lucide:briefcase',
        level: 2,
        order: 1,
        moduleCode: 'PM',
        children: [
          {
            id: 'pm-investment',
            parentId: 'pm-portfolio',
            name: 'Investment',
            title: '投资概览',
            icon: 'lucide:trending-up',
            path: '/pm/investment',
            level: 3,
            order: 1,
            moduleCode: 'PM',
          },
        ],
      },
      {
        id: 'pm-execution',
        parentId: 'pm',
        name: 'Execution',
        title: '项目执行',
        icon: 'lucide:play-circle',
        level: 2,
        order: 2,
        moduleCode: 'PM',
        children: [
          {
            id: 'pm-progress',
            parentId: 'pm-execution',
            name: 'Progress',
            title: '进度跟踪',
            icon: 'lucide:activity',
            path: '/pm/progress',
            level: 3,
            order: 1,
            moduleCode: 'PM',
          },
        ],
      },
    ],
  },
  {
    id: 'rd',
    name: 'RD',
    title: 'RD (研发管理)',
    icon: 'lucide:flask',
    level: 1,
    order: 8,
    moduleCode: 'RD',
    children: [
      {
        id: 'rd-plm',
        parentId: 'rd',
        name: 'PLM',
        title: '产品生命周期',
        icon: 'lucide:git-branch',
        level: 2,
        order: 1,
        moduleCode: 'RD',
        children: [
          {
            id: 'rd-ecr',
            parentId: 'rd-plm',
            name: 'ECR',
            title: '变更管理',
            icon: 'lucide:git-pull-request',
            path: '/rd/ecr',
            level: 3,
            order: 1,
            moduleCode: 'RD',
          },
        ],
      },
    ],
  },
  {
    id: 'am',
    name: 'AM',
    title: 'AM (资产管理)',
    icon: 'lucide:hard-drive',
    level: 1,
    order: 9,
    moduleCode: 'AM',
    children: [
      {
        id: 'am-registry',
        parentId: 'am',
        name: 'Registry',
        title: '资产台账',
        icon: 'lucide:database',
        level: 2,
        order: 1,
        moduleCode: 'AM',
        children: [
          {
            id: 'am-history',
            parentId: 'am-registry',
            name: 'History',
            title: '资产全生命周期',
            icon: 'lucide:history',
            path: '/am/history',
            level: 3,
            order: 1,
            moduleCode: 'AM',
          },
        ],
      },
      {
        id: 'am-maintenance',
        parentId: 'am',
        name: 'Maintenance',
        title: '维护管理',
        icon: 'lucide:wrench',
        level: 2,
        order: 2,
        moduleCode: 'AM',
        children: [
          {
            id: 'am-pm',
            parentId: 'am-maintenance',
            name: 'PM',
            title: '预防性维护',
            icon: 'lucide:shield-check',
            path: '/am/pm',
            level: 3,
            order: 1,
            moduleCode: 'AM',
          },
        ],
      },
    ],
  },
  {
    id: 'cs',
    name: 'CS',
    title: 'CS (客户服务)',
    icon: 'lucide:headphones',
    level: 1,
    order: 10,
    moduleCode: 'CS',
    children: [
      {
        id: 'cs-support',
        parentId: 'cs',
        name: 'Support',
        title: '服务支持',
        icon: 'lucide:life-buoy',
        level: 2,
        order: 1,
        moduleCode: 'CS',
        children: [
          {
            id: 'cs-field',
            parentId: 'cs-support',
            name: 'Field',
            title: '现场服务',
            icon: 'lucide:map-pin',
            path: '/cs/field',
            level: 3,
            order: 1,
            moduleCode: 'CS',
          },
        ],
      },
    ],
  },
  {
    id: 'org',
    name: 'ORG',
    title: 'ORG (企业组织)',
    icon: 'lucide:building-2',
    level: 1,
    order: 11,
    moduleCode: 'ORG',
    children: [
      {
        id: 'org-structure',
        parentId: 'org',
        name: 'Structure',
        title: '组织架构',
        icon: 'lucide:network',
        level: 2,
        order: 1,
        moduleCode: 'ORG',
        children: [
          {
            id: 'org-company',
            parentId: 'org-structure',
            name: 'Company',
            title: '公司代码',
            icon: 'lucide:building',
            path: '/org/company',
            level: 3,
            order: 1,
            moduleCode: 'ORG',
          },
          {
            id: 'org-plant',
            parentId: 'org-structure',
            name: 'Plant',
            title: '工厂定义',
            icon: 'lucide:factory',
            path: '/org/plant',
            level: 3,
            order: 2,
            moduleCode: 'ORG',
          },
        ],
      },
    ],
  },
  {
    id: 'sys',
    name: 'SYS',
    title: 'SYS (系统管理)',
    icon: 'lucide:settings',
    level: 1,
    order: 12,
    moduleCode: 'SYS',
    children: [
      {
        id: 'sys-core',
        parentId: 'sys',
        name: 'Core',
        title: '核心设置',
        icon: 'lucide:sliders',
        level: 2,
        order: 1,
        moduleCode: 'SYS',
        children: [
          {
            id: 'sys-params',
            parentId: 'sys-core',
            name: 'Params',
            title: '全局参数',
            icon: 'lucide:settings-2',
            path: '/sys/params',
            level: 3,
            order: 1,
            moduleCode: 'SYS',
          },
          {
            id: 'sys-notification',
            parentId: 'sys-core',
            name: 'Notification',
            title: '通知中心配置',
            icon: 'lucide:bell',
            path: '/sys/notification',
            level: 3,
            order: 2,
            moduleCode: 'SYS',
          },
        ],
      },
    ],
  },
];

export default eventHandler(async (event) => {
  const userinfo = verifyAccessToken(event);
  if (!userinfo) {
    return unAuthorizedResponse(event);
  }

  return useResponseSuccess(ERP_MENU_TREE);
});
